services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crawlguard
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - crawlguard-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crawlguard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crawlguard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crawlguard"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@crawlguard.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - crawlguard-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  crawlguard-network:
    driver: bridge